[theme]
primaryColor = "#167D8D"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#172B4D"
font = "sans serif"

[server]
maxUploadSize = 15
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
